version: "3.7"

services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "6101:6101"
    command: -p 6101

  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn run:app --reload --host 0.0.0.0 --port 6100 --proxy-headers"
    volumes:
      - .:/app
    ports:
      - "6100:6100"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A worker worker -B -l INFO
    env_file: .env
    depends_on:
      - web
      - redis
      - db

  redis:
    image: redis:6.2


volumes:
  postgres_data: